#!/bin/bash
# This is the code file for number-guess, and you can edit as you like.
clear

# Asks the user for a nickname, and starts the game by asking the user to enter the number
echo 'Please enter a nickname.'
read -p '> ' name


# Uncomment the line below to log the nicknames people enter, but only do this AFTER folowing the directions for this on the readme (https://github.com/TheHungrySomeone/Number-Guess/blob/main/README.md).

#echo $n >> /home/number/names.txt

echo 'Welcome, '$name'.  Please guess a number from 1 to 100.'
read -p '> ' guess
declare -i tries
tries=1
max=18

# Chooses a random number so the user doesn't have to edit this file manually
declare -i number
number=$(echo $(( $RANDOM % 100 + 1 )))

# All of this is for the computer to know if it's too high or too low.  This ends when the user picks the right number.
while [[ $guess -ne $number && $tries -ne $max ]]
do

if [[ $guess -gt $number  && $guess -le 100 ]]; then
  echo 'Too high.  Try again.'
  read -p '> ' guess
  tries+=1
fi

if [[ $guess -lt $number && $guess -ge 1 ]]; then
  echo 'Too low.  Try again.'
  read -p '> ' guess
  tries+=1
fi

if [[ $guess -lt 1 ]]; then
  echo 'That is less than 1.  Try again.'
  read -p '> ' guess
  tries+=1
fi

if [[ $guess -gt 100 ]]; then
  echo 'That is more than 100.  Try again.'
  read -p '> ' guess
  tries+=1
fi

done

# This is to end the game, and it asks if the user want's to play again.  If the user says no, then it wil simply exit the game, but if they say yes, it will start over this script.
if [[ $guess -eq $number ]]; then
  if [[ $tries == 1 ]]; then
  echo 'You won in '$tries' try!'
  read -p 'Would you like to to play again? [Y/n]: ' playagain
else
  echo 'You won in '$tries' tries!'
  read -p 'Would you like to to play again? [Y/n]: ' playagain
  fi
fi

if [[ $tries == $max ]]; then
	echo "You lost. You've guessed the maximum amount of times ("$max")."
	read -p 'Would you like to to play again? [Y/n]: ' playagain
fi

if [[ $playagain == n || $playagain == N ]]; then
echo "Bye, "$name"!  Come back soon!"
sleep 0.5s
exit 0
fi

if [[ $playagain == y || $playagain == Y ]]; then
exec bash "$0" "$@"
fi

# This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with this program. If not, see <https://www.gnu.org/licenses/>
